
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ercot:/usr/src/app/out
      - ercot_db:/usr/src/app/data
    environment:
      - APP_MODE=prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  ercot:
  ercot_db: